import { ApiProperty } from '@nestjs/swagger';

export class SellerPerformanceDto {
  @ApiProperty({ description: 'User ID of the seller' })
  userId: string;

  @ApiProperty({ description: 'Seller name' })
  sellerName: string;

  @ApiProperty({ description: 'Total number of sales' })
  totalSales: number;

  @ApiProperty({ description: 'Total products sold quantity' })
  totalProductsSold: number;

  @ApiProperty({ description: 'Total revenue generated by this seller' })
  totalRevenue: number;

  @ApiProperty({ description: 'Average sale value' })
  averageSaleValue: number;
} 