version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=sales_management
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=1d
      - ADMIN_EMAIL=admin@example.com
      - RESET_PASSWORD_EXPIRATION=10m
    command: npm run start:dev

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 